sudo: false
language: node_js

branches:
  only:
    - master

node_js:
  - node

after_success:
  - npm run semantic-release

script:
  - npm run lint
  - npm run build

notifications:
  email: false
